# Generated by Django 3.2.4 on 2021-07-20 21:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(validators=[blog.models.validate_comment_text]),
        ),
    ]
